### ISSUE TITLE
Upload to wemos

### ISSUE THREAD

**Issue by maxalmeida81** [ThomasMout/Arduino-vMix-tally#1]
Hi Thomas, how are you. First of all, 
![89228832-B755-4407-A3D3-1E0CE093263C](https://user-images.githubusercontent.com/57974819/70367363-3bae4500-186d-11ea-8150-8b239779bed3.jpeg)
![3FE0C572-E7B8-4587-8318-F31E37354F99](https://user-images.githubusercontent.com/57974819/70367364-3bae4500-186d-11ea-84b4-a44fac925651.jpeg)
![6774187E-AEDE-4797-886B-C30E05A33EAC](https://user-images.githubusercontent.com/57974819/70367365-3bae4500-186d-11ea-9f31-3a6a4f173e35.jpeg)
![C38F8F38-2A43-420B-9EC2-F2A62467485A](https://user-images.githubusercontent.com/57974819/70367366-3bae4500-186d-11ea-9901-bc42e8d539ee.jpeg)

congratulations for the project, i need something like that a couple months ago and I found your project. So I have a problem, I can’t upload the code... I can’t upload statistics files... can you explain better... I can’t find the option Tools > ESP8266 Sketch Data Upload in the Arduino IDE. my Arduino IDE is 1.8.10. I tried install 1.6.6 and did something I found in internet and I got this option, but with errors... thanks for your help! I will attach some pictures with errors.

**Comment by ThomasMout** [comment]
Hi,
Thanks for trying out this tally solution!

There are a few things I noticed when looking at you're images.

First you could try and update your boards and libraries as the IDE suggests in the first image on the bottom left.

A second option is to select the board _Wemos D1 R2_, it's very similar to the one you've selected now but not the same.

Please let me know if these options help you or if there is anything else I can help you with.

**Comment by maxalmeida81** [comment]
Hi Thomas, so I’m updating the boards now, and about the board selected, I don’t have any other option like that. If I update everything it’s will show me? Thanks again!

**Comment by maxalmeida81** [comment]
![80D70E32-88A9-4D35-A858-D95116CFABC5](https://user-images.githubusercontent.com/57974819/70378399-f9791800-18ed-11ea-8666-8f7279336184.jpeg)

**Comment by maxalmeida81** [comment]
Hi Thomas, I got upload the sketch. So now I gonna try to work with my vMix. Thanks!

**Comment by maxalmeida81** [comment]
One more question, 
![9A64F5DB-6CED-4502-8835-91CFEEDFCC12](https://user-images.githubusercontent.com/57974819/70380655-c7c37980-190c-11ea-8599-e6380257dab1.png)

Here I put my wifi network the same vMix? And the ip of vMix and the channel of tally?

Thanks!

**Comment by ThomasMout** [comment]
Hi, 
Sorry for the delayed answer. I've been a bit busy.

Yes that is correct. The SSID must be from the same network as the vMix instance. And the vMix hostname can be either the name of the computer on the network or it's ip address.

If you have any more questions, please let me know.
