### ISSUE TITLE
Use tri-colour LED instead of matrix?

### ISSUE THREAD

**Issue by andrewhearn** [ThomasMout/Arduino-vMix-tally#4]
It would be good if the s/w had support to drive a couple of dual or tri-colour LEDs instead of the LED matrix - this would allow having a couple of big bright LEDs facing the stage and one facing the camera operator - using red/green for live/preview etc, would be good.

**Comment by ThomasMout** [comment]
Hi andrewhearn,

Thank you for your suggestion!
Unfortunately I don't think it will fit this specific repository. Feel free to fork this repo to your own for additions like this.
